name: go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  go:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-go@7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - uses: golangci/golangci-lint-action@9.3.0
        with:
          version: v2.12.2 # match local version
      - run: make fmt-check
      - run: go test -race -cover ./...
      - run: make build
